N = int(input("Entrez un entier supérieur à 0 : "))
for i in range(1,N+1):
    print(i, "x 1 =", i*1)
    print(i, "x 2 =", i*2)
    print(i, "x 3 =", i*3)
    print(i, "x 4 =", i*4)
    print(i, "x 5 =", i*5)
    print(i, "x 6 =", i*6)
    print(i, "x 7 =", i*7)
    print(i, "x 8 =", i*8)
    print(i, "x 9 =", i*9)
    print(i, "x 10 =", i*10)
    print( )